export const Maps = [
	"de_mirage",
	"de_anubis",
	"de_inferno",
	"de_dust2",
	"de_overpass",
	"de_nuke",
	"de_vertigo",
	"de_ancient",
	"de_train",
	"de_cache",
	"de_cobblestone",
	"de_canals",
	"cs_office",
	"cs_italy",
	"de_aztec",
	"cs_agency",
	"de_jura",
	"de_grail",
	"de_tuscan",
	"de_season",
] as const;
export type Map = (typeof Maps)[number];

export const MapLabel: Record<Map, string> = {
	de_mirage: "Mirage",
	de_anubis: "Anubis",
	de_inferno: "Inferno",
	de_dust2: "Dust II",
	de_overpass: "Overpass",
	de_nuke: "Nuke",
	de_vertigo: "Vertigo",
	de_ancient: "Ancient",
	de_train: "Train",
	de_canals: "Canals",
	cs_office: "Office",
	cs_italy: "Italy",
	de_cobblestone: "Cobblestone",
	de_cache: "Cache",
	de_aztec: "Aztec",
	cs_agency: "Agency",
	de_jura: "Jura",
	de_grail: "Grail",
	de_season: "Season",
	de_tuscan: "Tuscan",
};

export const MapAlias: Record<Map, string> = {
	de_mirage: "mrg",
	de_anubis: "anb",
	de_inferno: "inf",
	de_dust2: "d2",
	de_overpass: "ovp",
	de_nuke: "nuke",
	de_vertigo: "vtg",
	de_ancient: "anc",
	de_train: "trn",
	de_canals: "can",
	cs_office: "office",
	cs_italy: "italy",
	de_cobblestone: "cob",
	de_cache: "cache",
	de_aztec: "azt",
	cs_agency: "agency",
	de_jura: "jura",
	de_grail: "grail",
	de_season: "ssn",
	de_tuscan: "tcn",
};
